### Site Settings ###
title               : Yopi Pilawan
description         : |
                      Halo.
                      Lihat proyek, portfolio, tulisan dan profilku di menu pojok kanan atas.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : helmiau/helmiau.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : helmiau/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md**


### Author Info ###
author:
  name              : Yopi Pilawan
  image             : https://i.ibb.co.com/v2Zt3bX/photo-6115917418598614313-y.jpg
  image_about       : https://i.ibb.co.com/v2Zt3bX/photo-6115917418598614313-y.jpg
# behance           : helmiamirudin
# dribbble          : helmiau
  email             : yofi.pilawan@gmail.com
  facebook          : yofi.shz
#  github            : helmiau
# gitlab            : your_username
  instagram         : yopi.shz
#  twitter           : helmiau
#  youtube           : helmilaw
  whatsapp          : 6285155153923
  telegram          : kangyop
# kaggle            : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: helmiau                    # Your website Shortname on disqus


### Google Analytics ###
analytics:
  enabled: true                                        # Set true to enable google analytics
  google:
    tracking_id: G-7EH55WVF7X

### Google Adsense ###
### Get your publisher ID with https://www.google.com/adsense/new/u/0/pub-your_publisher_id/settings/account-information
### Replace "your_publisher_id" from url above, with your publisher id.
### Download ads.txt from tutorial here https://support.google.com/adsense/answer/7532444?hl=en then place it to same directory with this file.
adsense:
  enabled: true                                        # Set true to enable google Adsense
  google:
    publisher_id: ca-pub-7446272259355358
    ## get data_ad_slot from https://www.google.com/adsense/new/u/0/pub-your_publisher_id/myads/units
    data_ad_slot: 7067117361

### Google Translate ###
tagmanager:
  enabled: false                                        # Set true to enable google Adsense
  google:
    tag_id: GTM-5BQ3JVM

### Google Translate ###
translate:
  enabled: false                                        # Set true to enable google translate

### AdBlock Detection ###
adblock_detect:
  enabled: true                                        # Set true to enable adblock detection

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
